version: '3.7'
services:
  weaviate:
      container_name: weaviate
      command:
        - --host
        - 0.0.0.0
        - --port
        - '8080'
        - --scheme
        - http
      image: cr.weaviate.io/semitechnologies/weaviate:1.23.10
      ports:
        - 8080:8080
        - 50051:50051
      volumes:
        - ./db:/var/lib/weaviate
      restart: on-failure:0
      environment:
        QUERY_DEFAULTS_LIMIT: 25
        # Enables API key authentication.
        AUTHENTICATION_APIKEY_ENABLED: 'true'
        # List one or more keys, separated by commas. Each key corresponds to a specific user identity below.
        AUTHENTICATION_APIKEY_ALLOWED_KEYS: ${AUTHENTICATION_APIKEY_ALLOWED_KEYS}
        # List one or more user identities, separated by commas. Each identity corresponds to a specific key above.
        AUTHENTICATION_APIKEY_USERS: ${AUTHENTICATION_APIKEY_USERS}
        PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
        DEFAULT_VECTORIZER_MODULE: 'none'
        ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
        CLUSTER_HOSTNAME: 'node1'
